name = "lab-maya-informatika"
compatibility_date = "2026-06-16"
pages_build_output_dir = "dist"

# Variabel Lingkungan
[vars]
# Ganti dengan secret acak yang kuat saat deploy ke produksi
JWT_SECRET = "super-secret-key-untuk-lab-maya-2026"

# Konfigurasi D1 Database Binding
[[d1_databases]]
binding = "DBMateri"
database_name = "materi"
database_id = "603a510b-ad31-4ecd-9ace-85413529dce1" # Ganti dengan ID database D1 Anda dari dashboard
preview_database_id = "DB_Materi" # Untuk testing lokal (wrangler)
