name = "lab-maya-informatika"
compatibility_date = "2024-03-20"
pages_build_output_dir = "dist"

# Variabel Lingkungan
[vars]
# Ganti dengan secret acak yang kuat saat deploy ke produksi
JWT_SECRET = "super-secret-key-untuk-lab-maya-2026"

# Konfigurasi D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "lab-maya-db"
database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" # Ganti dengan ID database D1 Anda dari dashboard
preview_database_id = "DB" # Untuk testing lokal (wrangler)
